"""initial clover schema

Revision ID: 7b37c476ed18
Revises: 
Create Date: 2026-06-06 23:35:03.502431

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b37c476ed18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clover_challenges',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('badge_icon', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clover_destinations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('avg_cost_per_day', sa.Float(), nullable=True),
    sa.Column('adventure_score', sa.Float(), nullable=False),
    sa.Column('nature_score', sa.Float(), nullable=False),
    sa.Column('food_score', sa.Float(), nullable=False),
    sa.Column('culture_score', sa.Float(), nullable=False),
    sa.Column('photography_score', sa.Float(), nullable=False),
    sa.Column('relaxation_score', sa.Float(), nullable=False),
    sa.Column('luxury_score', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clover_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_clover_users_email'), 'clover_users', ['email'], unique=True)
    op.create_table('clover_dna',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('adventure_score', sa.Float(), nullable=False),
    sa.Column('nature_score', sa.Float(), nullable=False),
    sa.Column('food_score', sa.Float(), nullable=False),
    sa.Column('culture_score', sa.Float(), nullable=False),
    sa.Column('photography_score', sa.Float(), nullable=False),
    sa.Column('relaxation_score', sa.Float(), nullable=False),
    sa.Column('luxury_score', sa.Float(), nullable=False),
    sa.Column('personality_type', sa.String(length=100), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_countries', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clover_dna_user_id'), 'clover_dna', ['user_id'], unique=True)
    op.create_table('clover_itineraries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clover_itineraries_user_id'), 'clover_itineraries', ['user_id'], unique=False)
    op.create_table('clover_recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_hidden_gem', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['clover_destinations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clover_recommendations_destination_id'), 'clover_recommendations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_clover_recommendations_user_id'), 'clover_recommendations', ['user_id'], unique=False)
    op.create_table('clover_trips',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('trip_type', sa.Enum('adventure', 'leisure', 'business', 'cultural', 'nature', name='triptype'), nullable=False),
    sa.Column('attractions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clover_trips_user_id'), 'clover_trips', ['user_id'], unique=False)
    op.create_table('clover_user_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['clover_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clover_user_challenges_challenge_id'), 'clover_user_challenges', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_clover_user_challenges_user_id'), 'clover_user_challenges', ['user_id'], unique=False)
    op.create_table('clover_wrapped',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('card_url', sa.String(length=500), nullable=True),
    sa.Column('share_token', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clover_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_clover_wrapped_user_id'), 'clover_wrapped', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clover_wrapped_user_id'), table_name='clover_wrapped')
    op.drop_table('clover_wrapped')
    op.drop_index(op.f('ix_clover_user_challenges_user_id'), table_name='clover_user_challenges')
    op.drop_index(op.f('ix_clover_user_challenges_challenge_id'), table_name='clover_user_challenges')
    op.drop_table('clover_user_challenges')
    op.drop_index(op.f('ix_clover_trips_user_id'), table_name='clover_trips')
    op.drop_table('clover_trips')
    op.drop_index(op.f('ix_clover_recommendations_user_id'), table_name='clover_recommendations')
    op.drop_index(op.f('ix_clover_recommendations_destination_id'), table_name='clover_recommendations')
    op.drop_table('clover_recommendations')
    op.drop_index(op.f('ix_clover_itineraries_user_id'), table_name='clover_itineraries')
    op.drop_table('clover_itineraries')
    op.drop_index(op.f('ix_clover_dna_user_id'), table_name='clover_dna')
    op.drop_table('clover_dna')
    op.drop_index(op.f('ix_clover_users_email'), table_name='clover_users')
    op.drop_table('clover_users')
    op.drop_table('clover_destinations')
    op.drop_table('clover_challenges')
    # ### end Alembic commands ###
